services:
  mongo:
    image: mongo:7
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: dev-tools-hub

  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      PORT: 3001
      MONGODB_URI: mongodb://mongo:27017/dev-tools-hub
      JWT_SECRET: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YzQ3MjQxNTM1ODZmODdhYzQ0ZWU1NSIsImlhdCI6MTc3NDQ4MjMzNywiZXhwIjoxNzc0NDg1OTM3fQ.239-GF0zZG5uf24TZ6ADqhlNeJGcqiOcdJE5X65UX7M
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongo-data: